name: okr_os
description: 'A new Flutter project. Created by Slidy'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flare_flutter: ^2.0.3
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^1.2.4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  effective_dart: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # 1.0x = mdpi, 2.0x = xhdpi, 3.0x = xxhdpi, 4.0x = xxxhdpi
  assets:
    - assets/loading_4dots.flr
    - assets/loading_credifit.flr
